MASTER_IP=localhost
REDUCER_IP=localhost
SRG_IP=localhost
MASTER_PORT=1234
REDUCER_PORT=4444
SRG_PORT=5555


# MASTER_IP=192.168.1.100  # Η IP του laptop που θα τρέχει τον Master
# REDUCER_IP=192.168.1.100 # Η IP του laptop που θα τρέχει τον Reducer
# SRG_IP=192.168.1.100     # Η IP του laptop που θα τρέχει τον SRG
# MASTER_PORT=1234
# REDUCER_PORT=4444
# SRG_PORT=5555